# Introduction {.unnumbered}

This is a book that contains all code to reproduce figures related to spatial analysis of TCR data associated with Afeyan, Nagler & Tu, et al (2025)

Note that while the code is identical, this book was rendered after final manuscript figures were generated and thus minor differences may arise, particularly for steps that are non-deterministic or rely on random number generators. 

## Tertiary lymphoid structures are reservoirs of stem-like tumor-specific T cells in renal cell carcinoma {.unnumbered}
Alexander B. Afeyan†, Adi Nagler†, Chloe R. Tu†, Gabriel Roberti De Oliveira, Berkay Simsek, Maxwell D. Seager, Nourhan El Ahmar, Haley E. Sax, Emma Lin, Amit Sud, Mehdi Borji, Cleo Forman, Sophia Liu, Patrick A. Ott, Toni K. Choueiri, Jennifer G. Abelin, Richard Burack, Shuqiang Li, Kenneth J. Livak, Svitlana Tyekucheva, Derin B. Keskin, Fei Chen, Michael B. Atkins, Jeremy M. Simon, Sabina Signoretti, Giacomo Oliveira°, David A. Braun‡°, Catherine J. Wu‡°

### Abstract {.unnumbered}
Tertiary lymphoid structures (TLS) are associated with improved response to immune checkpoint blockade across solid tumors1–3, but how they impact the phenotypic properties of tumor-specific T cells remains unknown. Across 24 treatment-naïve renal cell carcinoma (RCC) tumors, TLS-containing tumors were more heavily infiltrated by exhausted CD8+ T cells with a reduced terminal exhaustion transcriptional program compared to TLS- tumors. Specificity screening of 554 T cell clonotypes expanded within the microenvironment of 6 RCC tumors revealed 82 TCRs reactive against tumor cells and/or RCC antigens. A subset of tumor-specific T cell clonotypes (12%) was enriched within TLS, and these expressed an increased program of stem-like progenitor exhaustion, associated with favorable anti-tumor immunity. However, in 60 independent RCC tumors, macrophages within tumor margins of TLS-containing tumors bore an inferred immunosuppressive phenotype, and were colocalized with exhausted putative tumor-reactive T cells in a subgroup that was further analyzed, thus supporting this mode of immune evasion as a counterbalance to T cell immune pressure. Our data reveal TLS as reservoirs of tumor-specific T cells with stem-like progenitor features that could be leveraged by T cell immunotherapies.