---
title: "Untitled"
author: "Chloe R. Tu"
date: "2026-03-03"
output: html_document
---

# Libraries
```{r}
library(Seurat)
library(anndata)
library(reticulate)
library(wesanderson)
library(dplyr)
library(stringr)
library(clustree)
library(readxl)
library(reshape2)
library(ggplotify)
library(cowplot)
library(comparator)
library(ggpointdensity)
library(ggvenn)
library(viridis)

area_fill <- readRDS("../objects/Area_fill.rds")
source("../source_scripts/slideseq_functions_main.R")

options(Seurat.object.assay.version = 'v5')
```

# Open objects with annotated areas
```{r}
P102TA_10_RNA <- readRDS("../objects/02_Puck10_102TA_TCR_RNA_area_121125.Rds")
P102TA_17_RNA <- readRDS("../objects/02_Puck17_102TA_TCR_RNA_area_121125.Rds")
P102TA_33_RNA <- readRDS("../objects/02_Puck33_102TA_TCR_RNA_area_121125.Rds")
P102TA_39_RNA <- readRDS("../objects/02_Puck39_102TA_TCR_RNA_area_121125.Rds")

P107TA_15_RNA <- readRDS("../objects/02_Puck15_107TA_TCR_RNA_area_121125.Rds")
P107TA_18_RNA <- readRDS("../objects/02_Puck18_107TA_TCR_RNA_area_121125.Rds")
P107TA_20_RNA <- readRDS("../objects/02_Puck20_107TA_TCR_RNA_area_121125.Rds")

P108TA_26_RNA <- readRDS("../objects/02_Puck26_108TA_TCR_RNA_area_121125.Rds")
P108TA_29_RNA <- readRDS("../objects/02_Puck29_108TA_TCR_RNA_area_121125.Rds")
P108TA_30_RNA <- readRDS("../objects/02_Puck30_108TA_TCR_RNA_area_121125.Rds")
P108TA_32_RNA <- readRDS("../objects/02_Puck32_108TA_TCR_RNA_area_121125.Rds")

P108TB_06_RNA <- readRDS("../objects/02_Puck06_108TB_TCR_RNA_area_121125.Rds")
P108TB_14_RNA <- readRDS("../objects/02_Puck14_108TB_TCR_RNA_area_121125.Rds")

P109TB_23_RNA <- readRDS("../objects/02_Puck23_109TB_TCR_RNA_area_121125.Rds")
P109TB_34_RNA <- readRDS("../objects/02_Puck34_109TB_TCR_RNA_area_121125.Rds")

P110TA_28_RNA <- readRDS("../objects/02_Puck28_110TA_TCR_RNA_area_121125.Rds")
P110TA_30_RNA <- readRDS("../objects/02_Puck30_110TA_TCR_RNA_area_121125.Rds")

P111TA_32_RNA <- readRDS("../objects/02_Puck32_111TA_TCR_RNA_area_121125.Rds")
P111TA_37_RNA <- readRDS("../objects/02_Puck37_111TA_TCR_RNA_area_121125.Rds")
```

# Reorient pucks
```{r}
reorient_pucks <- function(obj){
  obj@images$image@coordinates$x <- obj$plot_x
  obj@images$image@coordinates$y <- -obj$plot_y
  
  return(obj)
}

P102TA_10_RNA <- reorient_pucks(P102TA_10_RNA)
P102TA_17_RNA <- reorient_pucks(P102TA_17_RNA)
P102TA_33_RNA <- reorient_pucks(P102TA_33_RNA)
P102TA_39_RNA <- reorient_pucks(P102TA_39_RNA)

P107TA_15_RNA <- reorient_pucks(P107TA_15_RNA)
P107TA_18_RNA <- reorient_pucks(P107TA_18_RNA)
P107TA_20_RNA <- reorient_pucks(P107TA_20_RNA)

P108TA_26_RNA <- reorient_pucks(P108TA_26_RNA)
P108TA_29_RNA <- reorient_pucks(P108TA_29_RNA)
P108TA_30_RNA <- reorient_pucks(P108TA_30_RNA)
P108TA_32_RNA <- reorient_pucks(P108TA_32_RNA)

P108TB_06_RNA <- reorient_pucks(P108TB_06_RNA)
P108TB_14_RNA <- reorient_pucks(P108TB_14_RNA)

P109TB_23_RNA <- reorient_pucks(P109TB_23_RNA)
P109TB_34_RNA <- reorient_pucks(P109TB_34_RNA)

P110TA_28_RNA <- reorient_pucks(P110TA_28_RNA)
P110TA_30_RNA <- reorient_pucks(P110TA_30_RNA)

P111TA_32_RNA <- reorient_pucks(P111TA_32_RNA)
P111TA_37_RNA <- reorient_pucks(P111TA_37_RNA)
```

# Remove empty areas
```{r}
P102TA_10_RNA <- subset(P102TA_10_RNA, area == "Empty", invert = TRUE)
P102TA_17_RNA <- subset(P102TA_17_RNA, area == "Empty", invert = TRUE)
P102TA_33_RNA <- subset(P102TA_33_RNA, area == "Empty", invert = TRUE)
P102TA_39_RNA <- subset(P102TA_39_RNA, area == "Empty", invert = TRUE)

P107TA_15_RNA <- subset(P107TA_15_RNA, area == "Empty", invert = TRUE)
P107TA_18_RNA <- subset(P107TA_18_RNA, area == "Empty", invert = TRUE)
P107TA_20_RNA <- subset(P107TA_20_RNA, area == "Empty", invert = TRUE)

P108TA_26_RNA <- subset(P108TA_26_RNA, area == "Empty", invert = TRUE)
P108TA_29_RNA <- subset(P108TA_29_RNA, area == "Empty", invert = TRUE)
P108TA_30_RNA <- subset(P108TA_30_RNA, area == "Empty", invert = TRUE)
P108TA_32_RNA <- subset(P108TA_32_RNA, area == "Empty", invert = TRUE)

P108TB_06_RNA <- subset(P108TB_06_RNA, area == "Empty", invert = TRUE)
P108TB_14_RNA <- subset(P108TB_14_RNA, area == "Empty", invert = TRUE)

P109TB_23_RNA <- subset(P109TB_23_RNA, area == "Empty", invert = TRUE)
P109TB_34_RNA <- subset(P109TB_34_RNA, area == "Empty", invert = TRUE)

P110TA_28_RNA <- subset(P110TA_28_RNA, area == "Empty", invert = TRUE)
P110TA_30_RNA <- subset(P110TA_30_RNA, area == "Empty", invert = TRUE)

P111TA_32_RNA <- subset(P111TA_32_RNA, area == "Empty", invert = TRUE)
P111TA_37_RNA <- subset(P111TA_37_RNA, area == "Empty", invert = TRUE)
```

# P102T pucks
```{r}
P102T_merged <- rbind(P102TA_10_RNA@meta.data[,c("clone_id", "area")], P102TA_17_RNA@meta.data[,c("clone_id", "area")], P102TA_33_RNA@meta.data[,c("clone_id", "area")], P102TA_39_RNA@meta.data[,c("clone_id", "area")])

P102T_total_clone_count <- count_clones_by_annotated_area(P102T_merged, get_unique_productive_clones(P102T_merged$clone_id)) %>%
  group_by(clone_id) %>%
  summarize(total_expansion = sum(count))

```

## P102TA 10
```{r}
P102TA_10_RNA <- add_total_clone_count_to_puck(P102TA_10_RNA, P102T_total_clone_count)

SpatialDimPlot(P102TA_10_RNA, group.by = "area", alpha = 0.2, stroke = 0) +
  geom_point(data = filter(P102TA_10_RNA@meta.data, P102TA_10_RNA$total_expansion > 0), aes(x = y, y = x-5200, color = log_total_expansion), size = 1.5, adjust = 100) +
  area_fill +
  scale_color_viridis()
```

## P102TA 17
```{r}
P102TA_17_RNA <- add_total_clone_count_to_puck(P102TA_17_RNA, P102T_total_clone_count)

SpatialDimPlot(P102TA_17_RNA, group.by = "area", alpha = 0.2, stroke = 0) +
  geom_point(data = filter(P102TA_17_RNA@meta.data, P102TA_17_RNA$total_expansion > 0), aes(x = y, y = x-5150, color = log_total_expansion), size = 1.5, adjust = 100) +
  area_fill +
  scale_color_viridis()
```

## P102TA 33
```{r}
P102TA_33_RNA <- add_total_clone_count_to_puck(P102TA_33_RNA, P102T_total_clone_count)

SpatialDimPlot(P102TA_33_RNA, group.by = "area", alpha = 0.2, stroke = 0) +
  geom_point(data = filter(P102TA_33_RNA@meta.data, P102TA_33_RNA$total_expansion > 0), aes(x = y, y = x-5200, color = log_total_expansion), size = 1.5, adjust = 100) +
  area_fill +
  scale_color_viridis()
```

## P102TA 39
```{r}
P102TA_39_RNA <- add_total_clone_count_to_puck(P102TA_39_RNA, P102T_total_clone_count)

SpatialDimPlot(P102TA_39_RNA, group.by = "area", alpha = 0.2, stroke = 0) +
  geom_point(data = filter(P102TA_39_RNA@meta.data, P102TA_39_RNA$total_expansion > 0), aes(x = y, y = x-4800, color = log_total_expansion), size = 1.5, adjust = 100) +
  area_fill +
  scale_color_viridis()
```

# P107T pucks
```{r}
P107T_merged <- rbind(P107TA_15_RNA@meta.data[,c("clone_id", "area")], P107TA_18_RNA@meta.data[,c("clone_id", "area")], P107TA_20_RNA@meta.data[,c("clone_id", "area")])

P107T_total_clone_count <- count_clones_by_annotated_area(P107T_merged, get_unique_productive_clones(P107T_merged$clone_id)) %>%
  group_by(clone_id) %>%
  summarize(total_expansion = sum(count))

```

## P107TA 15
```{r}
P107TA_15_RNA <- add_total_clone_count_to_puck(P107TA_15_RNA, P107T_total_clone_count)

SpatialDimPlot(P107TA_15_RNA, group.by = "area", alpha = 0.2, stroke = 0) +
  geom_point(data = filter(P107TA_15_RNA@meta.data, P107TA_15_RNA$total_expansion > 0), aes(x = y, y = x-5250, color = log_total_expansion), size = 1.5, adjust = 100) +
  area_fill +
  scale_color_viridis()
```

## P107TA 18
```{r}
P107TA_18_RNA <- add_total_clone_count_to_puck(P107TA_18_RNA, P107T_total_clone_count)

SpatialDimPlot(P107TA_18_RNA, group.by = "area", alpha = 0.2, stroke = 0) +
  geom_point(data = filter(P107TA_18_RNA@meta.data, P107TA_18_RNA$total_expansion > 0), aes(x = y, y = x-4800, color = log_total_expansion), size = 1.5, adjust = 100) +
  area_fill +
  scale_color_viridis()
```

## P107TA 20
```{r}
P107TA_20_RNA <- add_total_clone_count_to_puck(P107TA_20_RNA, P107T_total_clone_count)

SpatialDimPlot(P107TA_20_RNA, group.by = "area", alpha = 0.2, stroke = 0) +
  geom_point(data = filter(P107TA_20_RNA@meta.data, P107TA_20_RNA$total_expansion > 0), aes(x = y, y = x-5200, color = log_total_expansion), size = 1.5, adjust = 100) +
  area_fill +
  scale_color_viridis()
```

# P108T pucks
```{r}
P108T_merged <- rbind(P108TA_26_RNA@meta.data[,c("clone_id", "area")], P108TA_29_RNA@meta.data[,c("clone_id", "area")], P108TA_30_RNA@meta.data[,c("clone_id", "area")], P108TA_32_RNA@meta.data[,c("clone_id", "area")], P108TB_06_RNA@meta.data[,c("clone_id", "area")], P108TB_14_RNA@meta.data[,c("clone_id", "area")])

P108T_total_clone_count <- count_clones_by_annotated_area(P108T_merged, get_unique_productive_clones(P108T_merged$clone_id)) %>%
  group_by(clone_id) %>%
  summarize(total_expansion = sum(count))

```

## P108TA 26
```{r}
P108TA_26_RNA <- add_total_clone_count_to_puck(P108TA_26_RNA, P108T_total_clone_count)

SpatialDimPlot(P108TA_26_RNA, group.by = "area", alpha = 0.2, stroke = 0) +
  geom_point(data = filter(P108TA_26_RNA@meta.data, P108TA_26_RNA$total_expansion > 0), aes(x = y, y = x-5050, color = log_total_expansion), size = 1.5, adjust = 100) +
  area_fill +
  scale_color_viridis()
```

## P108TA 29
```{r}
P108TA_29_RNA <- add_total_clone_count_to_puck(P108TA_29_RNA, P108T_total_clone_count)

SpatialDimPlot(P108TA_29_RNA, group.by = "area", alpha = 0.2, stroke = 0) +
  geom_point(data = filter(P108TA_29_RNA@meta.data, P108TA_29_RNA$total_expansion > 0), aes(x = y, y = x-5100, color = log_total_expansion), size = 1.5, adjust = 100) +
  area_fill +
  scale_color_viridis()
```

## P108TA 30
```{r}
P108TA_30_RNA <- add_total_clone_count_to_puck(P108TA_30_RNA, P108T_total_clone_count)

SpatialDimPlot(P108TA_30_RNA, group.by = "area", alpha = 0.2, stroke = 0) +
  geom_point(data = filter(P108TA_30_RNA@meta.data, P108TA_30_RNA$total_expansion > 0), aes(x = y, y = x-5000, color = log_total_expansion), size = 1.5, adjust = 100) +
  area_fill +
  scale_color_viridis()
```

## P108TA 32
```{r}
P108TA_32_RNA <- add_total_clone_count_to_puck(P108TA_32_RNA, P108T_total_clone_count)

SpatialDimPlot(P108TA_32_RNA, group.by = "area", alpha = 0.2, stroke = 0) +
  geom_point(data = filter(P108TA_32_RNA@meta.data, P108TA_32_RNA$total_expansion > 0), aes(x = y, y = x-5200, color = log_total_expansion), size = 1.5, adjust = 100) +
  area_fill +
  scale_color_viridis()
```

## P108TB 6
```{r}
P108TB_06_RNA <- add_total_clone_count_to_puck(P108TB_06_RNA, P108T_total_clone_count)

SpatialDimPlot(P108TB_06_RNA, group.by = "area", alpha = 0.2, stroke = 0) +
  geom_point(data = filter(P108TB_06_RNA@meta.data, P108TB_06_RNA$total_expansion > 0), aes(x = y, y = x-4900, color = log_total_expansion), size = 1.5, adjust = 100) +
  area_fill +
  scale_color_viridis()
```

## P108TB 14
```{r}
P108TB_14_RNA <- add_total_clone_count_to_puck(P108TB_14_RNA, P108T_total_clone_count)

SpatialDimPlot(P108TB_14_RNA, group.by = "area", alpha = 0.2, stroke = 0) +
  geom_point(data = filter(P108TB_14_RNA@meta.data, P108TB_14_RNA$total_expansion > 0), aes(x = y, y = x-5250, color = log_total_expansion), size = 1.5, adjust = 100) +
  area_fill +
  scale_color_viridis()
```

# P109T pucks
```{r}
P109T_merged <- rbind(P109TB_23_RNA@meta.data[,c("clone_id", "area")], P109TB_34_RNA@meta.data[,c("clone_id", "area")])

P109T_total_clone_count <- count_clones_by_annotated_area(P109T_merged, get_unique_productive_clones(P109T_merged$clone_id)) %>%
  group_by(clone_id) %>%
  summarize(total_expansion = sum(count))

```

## P109TB 23
```{r}
P109TB_23_RNA <- add_total_clone_count_to_puck(P109TB_23_RNA, P109T_total_clone_count)

SpatialDimPlot(P109TB_23_RNA, group.by = "area", alpha = 0.2, stroke = 0) +
  geom_point(data = filter(P109TB_23_RNA@meta.data, P109TB_23_RNA$total_expansion > 0), aes(x = y, y = x-5150, color = log_total_expansion), size = 1.5, adjust = 100) +
  area_fill +
  scale_color_viridis()
```

## P109TB 34
```{r}
P109TB_34_RNA <- add_total_clone_count_to_puck(P109TB_34_RNA, P109T_total_clone_count)

SpatialDimPlot(P109TB_34_RNA, group.by = "area", alpha = 0.2, stroke = 0) +
  geom_point(data = filter(P109TB_34_RNA@meta.data, P109TB_34_RNA$total_expansion > 0), aes(x = y, y = x-5100, color = log_total_expansion), size = 1.5, adjust = 100) +
  area_fill +
  scale_color_viridis()
```

# P110T pucks
```{r}
P110T_merged <- rbind(P110TA_28_RNA@meta.data[,c("clone_id", "area")], P110TA_30_RNA@meta.data[,c("clone_id", "area")])

P110T_total_clone_count <- count_clones_by_annotated_area(P110T_merged, get_unique_productive_clones(P110T_merged$clone_id)) %>%
  group_by(clone_id) %>%
  summarize(total_expansion = sum(count))

```

## P110TA 28
```{r}
P110TA_28_RNA <- add_total_clone_count_to_puck(P110TA_28_RNA, P110T_total_clone_count)

SpatialDimPlot(P110TA_28_RNA, group.by = "area", alpha = 0.2, stroke = 0) +
  geom_point(data = filter(P110TA_28_RNA@meta.data, P110TA_28_RNA$total_expansion > 0), aes(x = y, y = x-4850, color = log_total_expansion), size = 1.5, adjust = 100) +
  area_fill +
  scale_color_viridis()
```

## P110TA 30
```{r}
P110TA_30_RNA <- add_total_clone_count_to_puck(P110TA_30_RNA, P110T_total_clone_count)

SpatialDimPlot(P110TA_30_RNA, group.by = "area", alpha = 0.2, stroke = 0) +
  geom_point(data = filter(P110TA_30_RNA@meta.data, P110TA_30_RNA$total_expansion > 0), aes(x = y, y = x-5000, color = log_total_expansion), size = 1.5, adjust = 100) +
  area_fill +
  scale_color_viridis()
```

# P111T pucks
```{r}
P111T_merged <- rbind(P111TA_32_RNA@meta.data[,c("clone_id", "area")], P111TA_37_RNA@meta.data[,c("clone_id", "area")])

P111T_total_clone_count <- count_clones_by_annotated_area(P111T_merged, get_unique_productive_clones(P111T_merged$clone_id)) %>%
  group_by(clone_id) %>%
  summarize(total_expansion = sum(count))

```

## P111TA 32
```{r}
P111TA_32_RNA <- add_total_clone_count_to_puck(P111TA_32_RNA, P111T_total_clone_count)

SpatialDimPlot(P111TA_32_RNA, group.by = "area", alpha = 0.2, stroke = 0) +
  geom_point(data = filter(P111TA_32_RNA@meta.data, P111TA_32_RNA$total_expansion > 0), aes(x = y, y = x-5150, color = log_total_expansion), size = 1.5, adjust = 100) +
  area_fill +
  scale_color_viridis()
```

## P111TA 37
```{r}
P111TA_37_RNA <- add_total_clone_count_to_puck(P111TA_37_RNA, P111T_total_clone_count)

SpatialDimPlot(P111TA_37_RNA, group.by = "area", alpha = 0.2, stroke = 0) +
  geom_point(data = filter(P111TA_37_RNA@meta.data, P111TA_37_RNA$total_expansion > 0), aes(x = y, y = x-5150, color = log_total_expansion), size = 1.5, adjust = 100) +
  area_fill +
  scale_color_viridis()
```

# Get session info
```{r}
sessionInfo()
```

