# Plot cell types spatially {#sec-spatial-features}

## Libraries
```{r setup, include=FALSE}
# library(spacexr)
library(Seurat)
library(dplyr)
library(spacexr)
library(tidyverse)
library(viridis)
library(colorblindr)

source("../source_scripts/slideseq_functions_main.R")

celltype_color <- scale_color_manual(name = "Cell type", values = c("B" = "#b17ba6", "Endothelial" = "#2e6a95", "Fibroblast" = "#5f7d5d", "Myeloid" = "#fb982d", "NK" = "#6fe23d", "T" = "black", "Tumor" = "#d9c7ba"))

options(Seurat.object.assay.version = 'v5')
```

## Open objects with annotated areas
```{r}
P102TA_10_RNA <- readRDS("../objects/02_Puck10_102TA_TCR_RNA_area_121125.Rds")
P102TA_17_RNA <- readRDS("../objects/02_Puck17_102TA_TCR_RNA_area_121125.Rds")
P102TA_33_RNA <- readRDS("../objects/02_Puck33_102TA_TCR_RNA_area_121125.Rds")
P102TA_39_RNA <- readRDS("../objects/02_Puck39_102TA_TCR_RNA_area_121125.Rds")

P107TA_15_RNA <- readRDS("../objects/02_Puck15_107TA_TCR_RNA_area_121125.Rds")
P107TA_18_RNA <- readRDS("../objects/02_Puck18_107TA_TCR_RNA_area_121125.Rds")
P107TA_20_RNA <- readRDS("../objects/02_Puck20_107TA_TCR_RNA_area_121125.Rds")

P108TA_26_RNA <- readRDS("../objects/02_Puck26_108TA_TCR_RNA_area_121125.Rds")
P108TA_29_RNA <- readRDS("../objects/02_Puck29_108TA_TCR_RNA_area_121125.Rds")
P108TA_30_RNA <- readRDS("../objects/02_Puck30_108TA_TCR_RNA_area_121125.Rds")
P108TA_32_RNA <- readRDS("../objects/02_Puck32_108TA_TCR_RNA_area_121125.Rds")

P108TB_06_RNA <- readRDS("../objects/02_Puck06_108TB_TCR_RNA_area_121125.Rds")
P108TB_14_RNA <- readRDS("../objects/02_Puck14_108TB_TCR_RNA_area_121125.Rds")

P109TB_23_RNA <- readRDS("../objects/02_Puck23_109TB_TCR_RNA_area_121125.Rds")
P109TB_34_RNA <- readRDS("../objects/02_Puck34_109TB_TCR_RNA_area_121125.Rds")

P110TA_28_RNA <- readRDS("../objects/02_Puck28_110TA_TCR_RNA_area_121125.Rds")
P110TA_30_RNA <- readRDS("../objects/02_Puck30_110TA_TCR_RNA_area_121125.Rds")

P111TA_32_RNA <- readRDS("../objects/02_Puck32_111TA_TCR_RNA_area_121125.Rds")
P111TA_37_RNA <- readRDS("../objects/02_Puck37_111TA_TCR_RNA_area_121125.Rds")
```

## Assign celltypes
```{r}
P102TA_10_RNA@meta.data <- P102TA_10_RNA@meta.data %>%
  assign_celltypes() %>%
  order_celltypes()
P102TA_10_RNA@meta.data %>%
  dplyr::count(assignment1)
P102TA_17_RNA@meta.data <- P102TA_17_RNA@meta.data %>%
  assign_celltypes() %>%
  order_celltypes()
P102TA_17_RNA@meta.data %>%
  dplyr::count(assignment1)
P102TA_33_RNA@meta.data <- P102TA_33_RNA@meta.data %>%
  assign_celltypes() %>%
  order_celltypes()
P102TA_33_RNA@meta.data %>%
  dplyr::count(assignment1)
P102TA_39_RNA@meta.data <- P102TA_39_RNA@meta.data %>%
  assign_celltypes() %>%
  order_celltypes()
P102TA_39_RNA@meta.data %>%
  dplyr::count(assignment1)

P107TA_15_RNA@meta.data <- P107TA_15_RNA@meta.data %>%
  assign_celltypes() %>%
  order_celltypes()
P107TA_15_RNA@meta.data %>%
  dplyr::count(assignment1)
P107TA_18_RNA@meta.data <- P107TA_18_RNA@meta.data %>%
  assign_celltypes() %>%
  order_celltypes()
P107TA_18_RNA@meta.data %>%
  dplyr::count(assignment1)
P107TA_20_RNA@meta.data <- P107TA_20_RNA@meta.data %>%
  assign_celltypes() %>%
  order_celltypes()
P107TA_20_RNA@meta.data %>%
  dplyr::count(assignment1)

P108TA_26_RNA@meta.data <- P108TA_26_RNA@meta.data %>%
  assign_celltypes() %>%
  order_celltypes()
P108TA_26_RNA@meta.data %>%
  dplyr::count(assignment1)
P108TA_29_RNA@meta.data <- P108TA_29_RNA@meta.data %>%
  assign_celltypes() %>%
  order_celltypes()
P108TA_29_RNA@meta.data %>%
  dplyr::count(assignment1)
P108TA_30_RNA@meta.data <- P108TA_30_RNA@meta.data %>%
  assign_celltypes() %>%
  order_celltypes()
P108TA_30_RNA@meta.data %>%
  dplyr::count(assignment1)
P108TA_32_RNA@meta.data <- P108TA_32_RNA@meta.data %>%
  assign_celltypes() %>%
  order_celltypes()
P108TA_32_RNA@meta.data %>%
  dplyr::count(assignment1)

P108TB_06_RNA@meta.data <- P108TB_06_RNA@meta.data %>%
  assign_celltypes() %>%
  order_celltypes()
P108TB_06_RNA@meta.data %>%
  dplyr::count(assignment1)
P108TB_14_RNA@meta.data <- P108TB_14_RNA@meta.data %>%
  assign_celltypes() %>%
  order_celltypes()
P108TB_14_RNA@meta.data %>%
  dplyr::count(assignment1)

P109TB_23_RNA@meta.data <- P109TB_23_RNA@meta.data %>%
  assign_celltypes() %>%
  order_celltypes()
P109TB_23_RNA@meta.data %>%
  dplyr::count(assignment1)
P109TB_34_RNA@meta.data <- P109TB_34_RNA@meta.data %>%
  assign_celltypes() %>%
  order_celltypes()
P109TB_34_RNA@meta.data %>%
  dplyr::count(assignment1)

P110TA_28_RNA@meta.data <- P110TA_28_RNA@meta.data %>%
  assign_celltypes() %>%
  order_celltypes()
P110TA_28_RNA@meta.data %>%
  dplyr::count(assignment1)
P110TA_30_RNA@meta.data <- P110TA_30_RNA@meta.data %>%
  assign_celltypes() %>%
  order_celltypes()
P110TA_30_RNA@meta.data %>%
  dplyr::count(assignment1)

P111TA_32_RNA@meta.data <- P111TA_32_RNA@meta.data %>%
  assign_celltypes() %>%
  order_celltypes()
P111TA_32_RNA@meta.data %>%
  dplyr::count(assignment1)
P111TA_37_RNA@meta.data <- P111TA_37_RNA@meta.data %>%
  assign_celltypes() %>%
  order_celltypes()
P111TA_37_RNA@meta.data %>%
  dplyr::count(assignment1)
```

# Plot RCTD calls

## P102 Puck10
```{r}
# Remove empty beads
P102TA_10_RNA <- subset(P102TA_10_RNA, subset = area == "Empty", invert = TRUE)

# Remove non-assigned beads
P102TA_10_assigned <- P102TA_10_RNA@meta.data %>%
  filter(!is.na(assignment1))

p10 <- ggplot() +
  geom_point(data = arrange(P102TA_10_assigned, assignment1_ord), alpha = 1, aes(x = plot_x, y = plot_y, color = assignment1), size = 0.4) +
  celltype_color +
  coord_fixed(ratio = 1, xlim = c(0, 5000), ylim = c(0, 5000)) +
  theme_void() +
  ggtitle("P102TA 10")

p10_sep <- ggplot() +
  geom_point(data = arrange(P102TA_10_assigned, assignment1_ord), alpha = 1, aes(x = plot_x, y = plot_y, color = assignment1), size = 0.1) +
  celltype_color +
  coord_fixed(ratio = 1, xlim = c(0, 5000), ylim = c(0, 5000)) +
  theme_void() +
  ggtitle("P102TA 10") +
  facet_wrap(~assignment1)

p10
p10_sep

cvd_grid(p10_sep)
```

## P102 Puck17
```{r}
# Remove empty beads
P102TA_17_RNA <- subset(P102TA_17_RNA, subset = area == "Empty", invert = TRUE)

# Remove non-assigned beads
P102TA_17_assigned <- P102TA_17_RNA@meta.data %>%
  filter(!is.na(assignment1))

p17 <- ggplot() +
  geom_point(data = arrange(P102TA_17_assigned, assignment1_ord), alpha = 1, aes(x = plot_x, y = plot_y, color = assignment1), size = 0.4) +
  celltype_color +
  coord_fixed(ratio = 1, xlim = c(0, 5000), ylim = c(0, 5000)) +
  theme_void() +
  ggtitle("P102TA 17")

p17_sep <- ggplot() +
  geom_point(data = arrange(P102TA_17_assigned, assignment1_ord), alpha = 1, aes(x = plot_x, y = plot_y, color = assignment1), size = 0.1) +
  celltype_color +
  coord_fixed(ratio = 1, xlim = c(0, 5000), ylim = c(0, 5000)) +
  theme_void() +
  ggtitle("P102TA 17") +
  facet_wrap(~assignment1)

p17
p17_sep

```

## P102 Puck33
```{r}
# Remove empty beads
P102TA_33_RNA <- subset(P102TA_33_RNA, subset = area == "Empty", invert = TRUE)

# Remove non-assigned beads
P102TA_33_assigned <- P102TA_33_RNA@meta.data %>%
  filter(!is.na(assignment1))

p33 <- ggplot() +
  geom_point(data = arrange(P102TA_33_assigned, assignment1_ord), alpha = 1, aes(x = plot_x, y = plot_y, color = assignment1), size = 0.4) +
  celltype_color +
  coord_fixed(ratio = 1, xlim = c(0, 5000), ylim = c(0, 5000)) +
  theme_void() +
  ggtitle("P102TA 33")

p33_sep <- ggplot() +
  geom_point(data = arrange(P102TA_33_assigned, assignment1_ord), alpha = 1, aes(x = plot_x, y = plot_y, color = assignment1), size = 0.1) +
  celltype_color +
  coord_fixed(ratio = 1, xlim = c(0, 5000), ylim = c(0, 5000)) +
  theme_void() +
  ggtitle("P102TA 33") +
  facet_wrap(~assignment1)

p33
p33_sep
```

## P102 Puck39
```{r}
# Remove empty beads
P102TA_39_RNA <- subset(P102TA_39_RNA, subset = area == "Empty", invert = TRUE)

# Remove non-assigned beads
P102TA_39_assigned <- P102TA_39_RNA@meta.data %>%
  filter(!is.na(assignment1))

p39 <- ggplot() +
  geom_point(data = arrange(P102TA_39_assigned, assignment1_ord), alpha = 1, aes(x = plot_x, y = plot_y, color = assignment1), size = 0.4) +
  celltype_color +
  coord_fixed(ratio = 1, xlim = c(0, 5000), ylim = c(0, 5000)) +
  theme_void() +
  ggtitle("P102TA 39")

p39_sep <- ggplot() +
  geom_point(data = arrange(P102TA_39_assigned, assignment1_ord), alpha = 1, aes(x = plot_x, y = plot_y, color = assignment1), size = 0.1) +
  celltype_color +
  coord_fixed(ratio = 1, xlim = c(0, 5000), ylim = c(0, 5000)) +
  theme_void() +
  ggtitle("P102TA 39") +
  facet_wrap(~assignment1)

p39
p39_sep
```

## P107 Puck15
```{r}
# Remove empty beads
P107TA_15_RNA <- subset(P107TA_15_RNA, subset = area == "Empty", invert = TRUE)

# Remove non-assigned beads
P107TA_15_assigned <- P107TA_15_RNA@meta.data %>%
  filter(!is.na(assignment1))

p15 <- ggplot() +
  geom_point(data = arrange(P107TA_15_assigned, assignment1_ord), alpha = 1, aes(x = plot_x, y = plot_y, color = assignment1), size = 0.4) +
  celltype_color +
  coord_fixed(ratio = 1, xlim = c(0, 5000), ylim = c(0, 5000)) +
  theme_void() +
  ggtitle("P107TA 15")

p15_sep <- ggplot() +
  geom_point(data = arrange(P107TA_15_assigned, assignment1_ord), alpha = 1, aes(x = plot_x, y = plot_y, color = assignment1), size = 0.1) +
  celltype_color +
  coord_fixed(ratio = 1, xlim = c(0, 5000), ylim = c(0, 5000)) +
  theme_void() +
  ggtitle("P107TA 15") +
  facet_wrap(~assignment1)

p15
p15_sep
```

## P107 Puck18
```{r}
# Remove empty beads
P107TA_18_RNA <- subset(P107TA_18_RNA, subset = area == "Empty", invert = TRUE)

# Remove non-assigned beads
P107TA_18_assigned <- P107TA_18_RNA@meta.data %>%
  filter(!is.na(assignment1))

p18 <- ggplot() +
  geom_point(data = arrange(P107TA_18_assigned, assignment1_ord), alpha = 1, aes(x = plot_x, y = plot_y, color = assignment1), size = 0.4) +
  celltype_color +
  coord_fixed(ratio = 1, xlim = c(0, 5000), ylim = c(0, 5000)) +
  theme_void() +
  ggtitle("P107TA 18")

p18_sep <- ggplot() +
  geom_point(data = arrange(P107TA_18_assigned, assignment1_ord), alpha = 1, aes(x = plot_x, y = plot_y, color = assignment1), size = 0.1) +
  celltype_color +
  coord_fixed(ratio = 1, xlim = c(0, 5000), ylim = c(0, 5000)) +
  theme_void() +
  ggtitle("P107TA 18") +
  facet_wrap(~assignment1)

p18
p18_sep
```

## P107 Puck20
```{r}
# Remove empty beads
P107TA_20_RNA <- subset(P107TA_20_RNA, subset = area == "Empty", invert = TRUE)

# Remove non-assigned beads
P107TA_20_assigned <- P107TA_20_RNA@meta.data %>%
  filter(!is.na(assignment1))

p20 <- ggplot() +
  geom_point(data = arrange(P107TA_20_assigned, assignment1_ord), alpha = 1, aes(x = plot_x, y = plot_y, color = assignment1), size = 0.4) +
  celltype_color +
  coord_fixed(ratio = 1, xlim = c(0, 5000), ylim = c(0, 5000)) +
  theme_void() +
  ggtitle("P107TA 20")

p20_sep <- ggplot() +
  geom_point(data = arrange(P107TA_20_assigned, assignment1_ord), alpha = 1, aes(x = plot_x, y = plot_y, color = assignment1), size = 0.1) +
  celltype_color +
  coord_fixed(ratio = 1, xlim = c(0, 5000), ylim = c(0, 5000)) +
  theme_void() +
  ggtitle("P107TA 20") +
  facet_wrap(~assignment1)

p20
p20_sep
```

## P108 Puck26
```{r}
# Remove empty beads
P108TA_26_RNA <- subset(P108TA_26_RNA, subset = area == "Empty", invert = TRUE)

# Remove non-assigned beads
P108TA_26_assigned <- P108TA_26_RNA@meta.data %>%
  filter(!is.na(assignment1))

p26 <- ggplot() +
  geom_point(data = arrange(P108TA_26_assigned, assignment1_ord), alpha = 1, aes(x = plot_x, y = plot_y, color = assignment1), size = 0.4) +
  celltype_color +
  coord_fixed(ratio = 1, xlim = c(0, 5000), ylim = c(0, 5000)) +
  theme_void() +
  ggtitle("P108TA 26")

p26_sep <- ggplot() +
  geom_point(data = arrange(P108TA_26_assigned, assignment1_ord), alpha = 1, aes(x = plot_x, y = plot_y, color = assignment1), size = 0.1) +
  celltype_color +
  coord_fixed(ratio = 1, xlim = c(0, 5000), ylim = c(0, 5000)) +
  theme_void() +
  ggtitle("P108TA 26") +
  facet_wrap(~assignment1)

p26
p26_sep
```

## P108 Puck29
```{r}
# Remove empty beads
P108TA_29_RNA <- subset(P108TA_29_RNA, subset = area == "Empty", invert = TRUE)

# Remove non-assigned beads
P108TA_29_assigned <- P108TA_29_RNA@meta.data %>%
  filter(!is.na(assignment1))

p29 <- ggplot() +
  geom_point(data = arrange(P108TA_29_assigned, assignment1_ord), alpha = 1, aes(x = plot_x, y = plot_y, color = assignment1), size = 0.4) +
  celltype_color +
  coord_fixed(ratio = 1, xlim = c(0, 5000), ylim = c(0, 5000)) +
  theme_void() +
  ggtitle("P108TA 29")

p29_sep <- ggplot() +
  geom_point(data = arrange(P108TA_29_assigned, assignment1_ord), alpha = 1, aes(x = plot_x, y = plot_y, color = assignment1), size = 0.1) +
  celltype_color +
  coord_fixed(ratio = 1, xlim = c(0, 5000), ylim = c(0, 5000)) +
  theme_void() +
  ggtitle("P108TA 29") +
  facet_wrap(~assignment1)

p29
p29_sep
```

## P108 Puck30
```{r}
# Remove empty beads
P108TA_30_RNA <- subset(P108TA_30_RNA, subset = area == "Empty", invert = TRUE)

# Remove non-assigned beads
P108TA_30_assigned <- P108TA_30_RNA@meta.data %>%
  filter(!is.na(assignment1))

p30 <- ggplot() +
  geom_point(data = arrange(P108TA_30_assigned, assignment1_ord), alpha = 1, aes(x = plot_x, y = plot_y, color = assignment1), size = 0.4) +
  celltype_color +
  coord_fixed(ratio = 1, xlim = c(0, 5000), ylim = c(0, 5000)) +
  theme_void() +
  ggtitle("P108TA 30")

p30_sep <- ggplot() +
  geom_point(data = arrange(P108TA_30_assigned, assignment1_ord), alpha = 1, aes(x = plot_x, y = plot_y, color = assignment1), size = 0.1) +
  celltype_color +
  coord_fixed(ratio = 1, xlim = c(0, 5000), ylim = c(0, 5000)) +
  theme_void() +
  ggtitle("P108TA 30") +
  facet_wrap(~assignment1)

p30
p30_sep
```

## P108 Puck32
```{r}
# Remove empty beads
P108TA_32_RNA <- subset(P108TA_32_RNA, subset = area == "Empty", invert = TRUE)

# Remove non-assigned beads
P108TA_32_assigned <- P108TA_32_RNA@meta.data %>%
  filter(!is.na(assignment1))

p32 <- ggplot() +
  geom_point(data = arrange(P108TA_32_assigned, assignment1_ord), alpha = 1, aes(x = plot_x, y = plot_y, color = assignment1), size = 0.4) +
  celltype_color +
  coord_fixed(ratio = 1, xlim = c(0, 5000), ylim = c(0, 5000)) +
  theme_void() +
  ggtitle("P108TA 32")

p32_sep <- ggplot() +
  geom_point(data = arrange(P108TA_32_assigned, assignment1_ord), alpha = 1, aes(x = plot_x, y = plot_y, color = assignment1), size = 0.1) +
  celltype_color +
  coord_fixed(ratio = 1, xlim = c(0, 5000), ylim = c(0, 5000)) +
  theme_void() +
  ggtitle("P108TA 32") +
  facet_wrap(~assignment1)

p32
p32_sep
```

## P108 Puck06
```{r}
# Remove empty beads
P108TB_06_RNA <- subset(P108TB_06_RNA, subset = area == "Empty", invert = TRUE)

# Remove non-assigned beads
P108TB_06_assigned <- P108TB_06_RNA@meta.data %>%
  filter(!is.na(assignment1))

p06 <- ggplot() +
  geom_point(data = arrange(P108TB_06_assigned, assignment1_ord), alpha = 1, aes(x = plot_x, y = plot_y, color = assignment1), size = 0.4) +
  celltype_color +
  coord_fixed(ratio = 1, xlim = c(0, 5000), ylim = c(0, 5000)) +
  theme_void() +
  ggtitle("P108TB 06")

p06_sep <- ggplot() +
  geom_point(data = arrange(P108TB_06_assigned, assignment1_ord), alpha = 1, aes(x = plot_x, y = plot_y, color = assignment1), size = 0.1) +
  celltype_color +
  coord_fixed(ratio = 1, xlim = c(0, 5000), ylim = c(0, 5000)) +
  theme_void() +
  ggtitle("P108TB 06") +
  facet_wrap(~assignment1)

p06
p06_sep
```

## P108 Puck14
```{r}
# Remove empty beads
P108TB_14_RNA <- subset(P108TB_14_RNA, subset = area == "Empty", invert = TRUE)

# Remove non-assigned beads
P108TB_14_assigned <- P108TB_14_RNA@meta.data %>%
  filter(!is.na(assignment1))

p14 <- ggplot() +
  geom_point(data = arrange(P108TB_14_assigned, assignment1_ord), alpha = 1, aes(x = plot_x, y = plot_y, color = assignment1), size = 0.4) +
  celltype_color +
  coord_fixed(ratio = 1, xlim = c(0, 5000), ylim = c(0, 5000)) +
  theme_void() +
  ggtitle("P108TB 14")

p14_sep <- ggplot() +
  geom_point(data = arrange(P108TB_14_assigned, assignment1_ord), alpha = 1, aes(x = plot_x, y = plot_y, color = assignment1), size = 0.1) +
  celltype_color +
  coord_fixed(ratio = 1, xlim = c(0, 5000), ylim = c(0, 5000)) +
  theme_void() +
  ggtitle("P108TB 14") +
  facet_wrap(~assignment1)

p14
p14_sep
```

## P109 Puck23
```{r}
# Remove empty beads
P109TB_23_RNA <- subset(P109TB_23_RNA, subset = area == "Empty", invert = TRUE)

# Remove non-assigned beads
P109TB_23_assigned <- P109TB_23_RNA@meta.data %>%
  filter(!is.na(assignment1))

p23 <- ggplot() +
  geom_point(data = arrange(P109TB_23_assigned, assignment1_ord), alpha = 1, aes(x = plot_x, y = plot_y, color = assignment1), size = 0.4) +
  celltype_color +
  coord_fixed(ratio = 1, xlim = c(0, 5000), ylim = c(0, 5000)) +
  theme_void() +
  ggtitle("P109TB 23")

p23_sep <- ggplot() +
  geom_point(data = arrange(P109TB_23_assigned, assignment1_ord), alpha = 1, aes(x = plot_x, y = plot_y, color = assignment1), size = 0.1) +
  celltype_color +
  coord_fixed(ratio = 1, xlim = c(0, 5000), ylim = c(0, 5000)) +
  theme_void() +
  ggtitle("P109TB 23") +
  facet_wrap(~assignment1)

p23
p23_sep
```

## P109 Puck34
```{r}
# Remove empty beads
P109TB_34_RNA <- subset(P109TB_34_RNA, subset = area == "Empty", invert = TRUE)

# Remove non-assigned beads
P109TB_34_assigned <- P109TB_34_RNA@meta.data %>%
  filter(!is.na(assignment1))

p34 <- ggplot() +
  geom_point(data = arrange(P109TB_34_assigned, assignment1_ord), alpha = 1, aes(x = plot_x, y = plot_y, color = assignment1), size = 0.4) +
  celltype_color +
  coord_fixed(ratio = 1, xlim = c(0, 5000), ylim = c(0, 5000)) +
  theme_void() +
  ggtitle("P109TB 34")

p34_sep <- ggplot() +
  geom_point(data = arrange(P109TB_34_assigned, assignment1_ord), alpha = 1, aes(x = plot_x, y = plot_y, color = assignment1), size = 0.1) +
  celltype_color +
  coord_fixed(ratio = 1, xlim = c(0, 5000), ylim = c(0, 5000)) +
  theme_void() +
  ggtitle("P109TB 34") +
  facet_wrap(~assignment1)

p34
p34_sep
```

## P110 Puck28
```{r}
# Remove empty beads
P110TA_28_RNA <- subset(P110TA_28_RNA, subset = area == "Empty", invert = TRUE)

# Remove non-assigned beads
P110TA_28_assigned <- P110TA_28_RNA@meta.data %>%
  filter(!is.na(assignment1))

p28 <- ggplot() +
  geom_point(data = arrange(P110TA_28_assigned, assignment1_ord), alpha = 1, aes(x = plot_x, y = plot_y, color = assignment1), size = 0.4) +
  celltype_color +
  coord_fixed(ratio = 1, xlim = c(0, 5000), ylim = c(0, 5000)) +
  theme_void() +
  ggtitle("P110TA 28")

p28_sep <- ggplot() +
  geom_point(data = arrange(P110TA_28_assigned, assignment1_ord), alpha = 1, aes(x = plot_x, y = plot_y, color = assignment1), size = 0.1) +
  celltype_color +
  coord_fixed(ratio = 1, xlim = c(0, 5000), ylim = c(0, 5000)) +
  theme_void() +
  ggtitle("P110TA 28") +
  facet_wrap(~assignment1)

p28
p28_sep
```

## P110 Puck30
```{r}
# Remove empty beads
P110TA_30_RNA <- subset(P110TA_30_RNA, subset = area == "Empty", invert = TRUE)

# Remove non-assigned beads
P110TA_30_assigned <- P110TA_30_RNA@meta.data %>%
  filter(!is.na(assignment1))

p110_p30 <- ggplot() +
  geom_point(data = arrange(P110TA_30_assigned, assignment1_ord), alpha = 1, aes(x = plot_x, y = plot_y, color = assignment1), size = 0.4) +
  celltype_color +
  coord_fixed(ratio = 1, xlim = c(0, 5000), ylim = c(0, 5000)) +
  theme_void() +
  ggtitle("P110TA 30")

p110_p30_sep <- ggplot() +
  geom_point(data = arrange(P110TA_30_assigned, assignment1_ord), alpha = 1, aes(x = plot_x, y = plot_y, color = assignment1), size = 0.1) +
  celltype_color +
  coord_fixed(ratio = 1, xlim = c(0, 5000), ylim = c(0, 5000)) +
  theme_void() +
  ggtitle("P110TA 30") +
  facet_wrap(~assignment1)

p110_p30
p110_p30_sep
```


## P111 Puck32
```{r}
# Remove empty beads
P111TA_32_RNA <- subset(P111TA_32_RNA, subset = area == "Empty", invert = TRUE)

# Remove non-assigned beads
P111TA_32_assigned <- P111TA_32_RNA@meta.data %>%
  filter(!is.na(assignment1))

p111_p32 <- ggplot() +
  geom_point(data = arrange(P111TA_32_assigned, assignment1_ord), alpha = 1, aes(x = plot_x, y = plot_y, color = assignment1), size = 0.4) +
  celltype_color +
  coord_fixed(ratio = 1, xlim = c(0, 5000), ylim = c(0, 5000)) +
  theme_void() +
  ggtitle("P111TA 32")

p111_p32_sep <- ggplot() +
  geom_point(data = arrange(P111TA_32_assigned, assignment1_ord), alpha = 1, aes(x = plot_x, y = plot_y, color = assignment1), size = 0.1) +
  celltype_color +
  coord_fixed(ratio = 1, xlim = c(0, 5000), ylim = c(0, 5000)) +
  theme_void() +
  ggtitle("P111TA 32") +
  facet_wrap(~assignment1)

p111_p32
p111_p32_sep
```

## P111 Puck37
```{r}
# Remove empty beads
P111TA_37_RNA <- subset(P111TA_37_RNA, subset = area == "Empty", invert = TRUE)

# Remove non-assigned beads
P111TA_37_assigned <- P111TA_37_RNA@meta.data %>%
  filter(!is.na(assignment1))

p37 <- ggplot() +
  geom_point(data = arrange(P111TA_37_assigned, assignment1_ord), alpha = 1, aes(x = plot_x, y = plot_y, color = assignment1), size = 0.4) +
  celltype_color +
  coord_fixed(ratio = 1, xlim = c(0, 5000), ylim = c(0, 5000)) +
  theme_void() +
  ggtitle("P111TA 37")

p37_sep <- ggplot() +
  geom_point(data = arrange(P111TA_37_assigned, assignment1_ord), alpha = 1, aes(x = plot_x, y = plot_y, color = assignment1), size = 0.1) +
  celltype_color +
  coord_fixed(ratio = 1, xlim = c(0, 5000), ylim = c(0, 5000)) +
  theme_void() +
  ggtitle("P111TA 37") +
  facet_wrap(~assignment1)

p37
p37_sep
```

# Get session info
```{r}
sessionInfo()
```
